-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY

-- 8월부터 10월까지
WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10' 
AND CAR_ID IN (
    -- 8월 부터 10월까지 총 대여횟수가 5회 이상인 차
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)
-- 월별, 차별
GROUP BY MONTH, CAR_ID
-- 월의 총 대여 횟수 0인경우 결과에서 제외
HAVING RECORDS >= 1
ORDER BY MONTH, CAR_ID DESC