-- 도서 판매량 합산
SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
# SELECT *
FROM BOOK B
JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
-- 2022 01
WHERE DATE_FORMAT(BS.SALES_DATE, '%Y-%m') = '2022-01'
-- 카테고리 별
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY