-- 코드를 입력하세요
SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE), 2) AS SCORE 
FROM REST_INFO A
JOIN REST_REVIEW B ON A.REST_ID = B.REST_ID
-- ID별로 묶음, GROUP BY 안하는 경우 모든 가게 SCORE의 평균을 구함
-- GROUP BY 사용 시 REST_ID별 SCORE를 구해줌
GROUP BY A.REST_ID 
HAVING A.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC