-- 코드를 입력하세요
SELECT 
B.REST_ID AS REST_ID,
B.REST_NAME AS REST_NAME, 
B.FOOD_TYPE AS FOOD_TYPE, 
B.FAVORITES AS FAVORITES, 
B.ADDRESS AS ADDRESS, 
ROUND(AVG(A.REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW A
JOIN REST_INFO B ON A.REST_ID = B.REST_ID
GROUP BY A.REST_ID
HAVING ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC